	<tr>
	<td colSpan="20" style="BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: outset; BORDER-LEFT-STYLE: outset; BORDER-BOTTOM-STYLE: none">
	<center>
	<table cellpadding = 10px><tr>
	<td><button onclick="window.location='SelectMember.php'">Search</button></td>
	<td><button onclick="window.location='DisplayMember.php?Action=NewAccount'">New Member</button></td>
	<td><button onclick="window.location='DisplayMember.php?Action=NewAccount&Staff=yes'">Staff Incentive</button></td>
	<td><button onclick="window.location='SelectGroup.php'">Group Loyalty</button></td>
	<td><button onclick="window.location='ShowUserHistory.php'">Latest Accounts</button></td>
	</tr></table>
	</center>
	<tr>
 	<td colSpan="20" height="400" style="BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: outset; BORDER-LEFT-STYLE: outset; BORDER-BOTTOM-STYLE: outset">
