	<tr>
	<td colSpan="20" style="BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: outset; BORDER-LEFT-STYLE: outset; BORDER-BOTTOM-STYLE: none">
	<center>
	<table cellpadding = 10px><tr>
	<td><button onclick="window.location='ManageUsers.php'">Manage Users</button></td>
	<td><button onclick="window.location='CreateUser.php'">New User</button></td>
	<td><button onclick="window.location='ManageUsers.php?ShowAll=true'">Show All</button></td>
	</tr></table>
	<center>
	</td>
	</tr>
	<tr>
 	<td colSpan="20" height="400" style="BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: outset; BORDER-LEFT-STYLE: outset; BORDER-BOTTOM-STYLE: outset">
