#!/bin/sh
#
# Before executing any script we use cd so that relative paths work
# according to a post on the php.net web site under include this
# is an issue when using cli
#

# First check that this process is not already stuck
LOCKFILE="/var/lock/LiabilityAccrual.lock"

if [ -f $LOCKFILE ]; then   ###> do not run multiple instances at the same time
        echo "LOCK File exists - Quitting"
        exit 0
fi

touch $LOCKFILE

#
# Mantis 818 Make Liability Accrual weekly
# 
# -- MRM 03/04/2009
#
cd /data/www/websites/texaco/RegularProcessing/MonthlyProcess
php -f LiabilityAccrual.php 2>&1 | tee -a /data/www/logs/Weekly.log

rm -vf $LOCKFILE