#!/bin/sh
#
# Before executing any script we use cd so that relative paths work
# according to a post on the php.net web site under include this
# is an issue when using cli
#

# First check that this process is not already stuck
LOCKFILE="/var/lock/StartOfMonth.lock"

if [ -f $LOCKFILE ]; then   ###> do not run multiple instances at the same time
        echo "LOCK File exists - Quitting"
        exit 0
fi

touch $LOCKFILE



#   Move the compower file to the processing area
mv /data/compower/uploads/RSMCSVDATA.DAT /data/www/websites/texaco/FileProcessing/Compower/RSMCSVDATA.DAT




#Create the new months transaction log tables

cd /data/www/websites/texaco/RegularProcessing/MonthlyProcess
php -f CreateNewTables.php 2>&1 | tee -a  /data/www/logs/CreateTables.log

#
# Mantis 2022 Move Liability Report to before Accrual
# 
# -- MRM 27 10 2010 mantis 2505
#

php -f CreateWorkingTables.php 2>&1 | tee -a  /data/www/logs/CreateTables.log

cd /data/www/websites/texaco/Reporting
php -f CreateLiablityReport.php 2>&1 | tee -a  /data/www/logs/Weekly.log

#

cd /data/www/websites/texaco/RegularProcessing/MonthlyProcess
php -f LiabilityAccrual.php 2>&1 | tee -a /data/www/logs/Weekly.log

#
#       26/08/2008
#       Next section added by Steve for Occam extracts ensuring that the RawKPI reporting tables are created for 
#       the first extract on the 3rd of the month.
#
#		11/12/2009 MRM		Mantis 1426 
#		CreateSegments already runs on Saturdays as part of the WeeklySegmentCode process
#
#

LOCKFILE2="/var/lock/WeeklySegmentCode.lock"
if [ ! -f $LOCKFILE2 ]; then
    cd /data/www/websites/texaco/Reporting
	php -f CreateSegments.php 2>&1 | tee -a  /data/www/logs/Weekly.log
	
	cd /data/www/websites/texaco/Issues/Accounts
	php -f NoSegmentCode.php 2>&1 | tee -a  /data/www/logs/Weekly.log
fi

rm -vf $LOCKFILE